In [22]:
import pandas as pd

In [23]:
data = {'name' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        'salary' : [100 , 200 , 300 , 400],
        'mail_id' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        'addr' : ['blr' , 'blr' , 'blr' , 'mum']
    }


In [24]:
df = pd.DataFrame(data)

In [25]:
df.loc[5:6]

Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [26]:
df.iloc[1:3,1:2]

salary
1     200
2     300

In [27]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [28]:
data1= {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [29]:
df1 = pd.DataFrame(data1)

In [30]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454    web dev 
3    656        6778       5656  blockchian

In [31]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [32]:
# string concatination
'sudh' + 'kumar'

'sudhkumar'

In [33]:
pd.concat([df,df1])   #horizontal concatination

name  salary             mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                 NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                 NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [34]:
pd.concat([df,df1],axis=1)

name  salary             mail_id addr  pf_nu  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  blr    234         234      23543   
1    krish     200    krish@ineuron.ai  blr     45         565      43543   
2   hitesh     300   hitesh@ineuron.ai  blr  54465         767        454   
3  tulesko     400  tulesko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [41]:
data2 = {'0' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        '1' : [100 , 200 , 300 , 400],
        '2' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        '3' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [42]:
data3= {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [43]:
df2 = pd.DataFrame(data2)

In [44]:
df3 = pd.DataFrame(data3)

In [45]:
pd.concat([df2,df3])

0     1                   2           3
0     sudh   100     sudh@ineuron.ai         blr
1    krish   200    krish@ineuron.ai         blr
2   hitesh   300   hitesh@ineuron.ai         blr
3  tulesko   400  tulesko@ineuron.ai         mum
0      234   234               23543          ds
1       45   565               43543     bigdata
2    54465   767                 454    web dev 
3      656  6778                5656  blockchian

In [46]:
data4 = {'emp_id':[101,102,103,104],
         'salary':[234,345,200,400],
         'pf':[23,34,56,78]
}

In [55]:
data5 = {'emp_id':[101,102,104,105],
         'mob_no':[3434,5656,767,878],
         'house_nu':[345,345,345,56]
}

In [56]:
df4 = pd.DataFrame(data4)

In [57]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [58]:
df5 = pd.DataFrame(data5)

In [59]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [60]:
pd.merge(df4,df5)

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [61]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [62]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [63]:
pd.merge(df4,df5,how='left')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [64]:
pd.merge(df4,df5,how='right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [65]:
data6 = {'emp_id1':[101,102,103,104],
         'salary':[234,345,200,400],
         'pf':[23,34,56,78]
}
data7 = {'emp_id2':[101,102,104,105],
         'mob_no':[3434,5656,767,878],
         'house_nu':[345,345,345,56]
}

In [66]:
df6 = pd.DataFrame(data6)
df7 = pd.DataFrame(data7)

In [69]:
pd.merge(df6,df7,left_on='emp_id1',right_on='emp_id2')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [74]:

data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105],
          'salary' : [234, 345,200,878],
          'house_nu' : [345,345,345,56]
    
}

In [75]:
df8 = pd.DataFrame(data8)
df9 = pd.DataFrame(data9)

In [76]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [77]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56

In [78]:
pd.merge(df8,df9,on=['emp_id','salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [90]:

data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data11  = {'emp_id2' : [101,102,104,105],
          'salary2' : [234, 345,200,878],
          'house_nu' : [345,345,345,56]
    
}

In [91]:
df10 = pd.DataFrame(data10,index=['a','b','c','d'])

In [92]:
df11 = pd.DataFrame(data11,index=['a','b','c','d'])

In [93]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [94]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
c      104      200       345
d      105      878        56

In [95]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23      101      234       345
b      102      345  34      102      345       345
c      103      200  56      104      200       345
d      104      400  78      105      878        56

In [99]:
df_sales = pd.read_csv('sales_data_final.csv')

In [100]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [102]:
def profit_flag(a):
    if a > 0:
        return 'positive'
    else:
        return 'negative'

In [103]:
profit_flag(-45)

'negative'

In [104]:
profit_flag(45)

'positive'

In [105]:
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)

In [106]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [107]:
df_sales['len_cust_name'] = df_sales['customer_name'].apply(len)

In [108]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...                                     product_name sales  \
0       Africa  ...                              Tenex Lockers, Blue   408   
1      Oceania  ...                         Acme Trimmer, High Speed   120   
2         EMEA  ...                          Tenex Box, Single Width    66   
3        North  ...                      Enermax Note Cards, Premium    45   
4      Oceania  ...                       Eldon Light Bulb, Duo Pack   114   
...        ...  ...                                              ...   ...   
51285     West  ...  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14   
51286   Africa  ...          Wilson Jones Hole Reinforcements, Clear     4   
51287  Central  ...           Hon Color Coded Labels, 5000 Label Set    26   
51288    North  ...           Hon Legal Exhibit Labels, Alphabetical     7   
51289     West  ...                              Bagged Rubber Bands     3   

      quantity discount    profit  shipping_cost  order_priority  year  \
0            2      0.0  106.1400          35.46          Medium  2011   
1            3      0.1   36.0360           9.72          Medium  2011   
2            4      0.0   29.6400           8.17            High  2011   
3            3      0.5  -26.0550           4.82            High  2011   
4            5      0.1   37.7700           4.70          Medium  2011   
...        ...      ...       ...            ...             ...   ...   
51285        2      0.2    4.5188           0.89          Medium  2014   
51286        1      0.0    0.4200           0.49          Medium  2014   
51287        3      0.0   12.3600           0.35          Medium  2014   
51288        1      0.0    0.5600           0.20          Medium  2014   
51289        3      0.2   -0.6048           0.17          Medium  2014   

       flag_profit len_cust_name  
0         positive            15  
1         positive            11  
2         positive            13  
3         negative            12  
4         positive            11  
...            ...           ...  
51285     positive            10  
51286     positive             9  
51287     positive            16  
51288     positive            13  
51289     negative            13  

[51290 rows x 23 columns]

In [109]:
def quantity_flag(a):
    if a < 10:
        return 'low'
    elif a >10 and a<20:
        return 'medium'
    else:
        return 'high'

In [111]:
df_sales['flag_quantity'] = df_sales['quantity'].apply(quantity_flag)

In [112]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     positive   
1        3      0.1   36.036          9.72          Medium  2011     positive   
2        4      0.0   29.640          8.17            High  2011     positive   
3        3      0.5  -26.055          4.82            High  2011     negative   
4        5      0.1   37.770          4.70          Medium  2011     positive   

   len_cust_name flag_quantity  
0             15           low  
1             11           low  
2             13           low  
3             12           low  
4             11           low  

[5 rows x 24 columns]

In [113]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda a:a**2)

In [114]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     positive   
1      0.1   36.036          9.72         Medium  2011     positive   
2      0.0   29.640          8.17           High  2011     positive   
3      0.5  -26.055          4.82           High  2011     negative   
4      0.1   37.770          4.70         Medium  2011     positive   

   len_cust_name  flag_quantity square_quantity  
0             15            low               4  
1             11            low               9  
2             13            low              16  
3             12            low               9  
4             11            low              25  

[5 rows x 25 columns]

In [115]:
import numpy as np

In [116]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [117]:
type(np.array([2,3,4,5,6]))  # 1d array

numpy.ndarray

In [118]:
np.array([[2,3,4],[5,6,7]]) # 2d array

array([[2, 3, 4],
       [5, 6, 7]])

In [119]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [120]:
l = [[1,2,3,4],[2,3,4,5]]
l[0][0]

1

In [124]:
a = np.array([3,4,5,6],ndmin=3)

In [125]:
a

array([[[3, 4, 5, 6]]])

In [126]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [127]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
arr.ndim

2

In [129]:
np.random.randint(1,10,(4,4))

array([[9, 5, 2, 7],
       [7, 2, 1, 6],
       [8, 4, 3, 1],
       [1, 7, 6, 6]])

In [130]:
np.random.randint(1,10,(4,4,2))

array([[[9, 8],
        [6, 6],
        [9, 2],
        [3, 8]],

       [[5, 9],
        [8, 6],
        [4, 4],
        [5, 9]],

       [[5, 4],
        [8, 4],
        [3, 3],
        [6, 7]],

       [[7, 8],
        [6, 1],
        [8, 7],
        [3, 8]]])